### ISSUE TITLE
Impossible to insert Tag pairs because of comma 

### ISSUE THREAD

**Issue by mbuyukkarakas** [intellitrend/zabbix-csv-host-import-module#12]
When I add multiple tag pairs, Excel or other editors are inserting ( ; ) as delimiter. And there is no way to change this with an comma ( , )
This makes impossible to insert multiple tag pairs
Must be developed a solution for this , I need to insert thousands of hosts with tags.

thank you

**Comment by intellitrend-team** [comment]
This is a good point. When a CSV file is written using `,` as delimiters, those other fields indeed can't be separated correctly anymore. We will need to improve the code so that both `;` and `,` are supported as delimiters and pick a different separator for the fields.

**Comment by intellitrend-team** [comment]
With the latest change, it is possible to choose between comma, semicolon and tabulator as a separator char. That should cover the most common CSV formats.

Some additional changes are still required so that the example CSV file will also use that separator when you download it. Right now, it is always using semicolon.
